completed: completed task 23
IgorNesterovich/TMS-WD-12 pull request #1
Opened 2024-02-12 06:48 UTC by IgorNesterovich

2024-02-14 19:12 UTC, FilipovskyAlex requested changes

2024-02-14 19:12 UTC, FilipovskyAlex commented on HW_23/routes/web.php
> +Route::get('/user/{id?}', function (?string $id = 'Пользователь анонимен') {
не особо корректно, все-таки id, во-первых, это обычно int, во-вторых - значение по ум. для id, это вообще не id)

2024-02-14 19:12 UTC, FilipovskyAlex commented on HW_23/routes/web.php
> +Route::get('/post/{slug?}', function () {
а чего slug необязателен?

2024-02-14 19:12 UTC, FilipovskyAlex commented on HW_23/routes/web.php
> +Route::get('/greet/{name?}', function (string $name = null) {
и тут зачем необязателен?

2024-02-14 19:12 UTC, FilipovskyAlex commented on HW_23/routes/web.php
> +Route::get('/api/users', function () {
тут подсказка, что это должен был бы быть api роут

2024-02-14 19:12 UTC, FilipovskyAlex commented on HW_23/app/Http/Controllers/CalculateController.php
> +    public function show($operation, $num1, $num2)
у тебя сейчас нет никакой проверки на вводимые query параметры, если я введу не те занчения, то может даже быть ошибка

2024-02-14 19:12 UTC, FilipovskyAlex commented on HW_23/routes/web.php
> +Route::get('/submit-contact-form/create', function () {
а этот роут зачем?

2024-02-19 05:13 UTC, IgorNesterovich commented on HW_23/routes/web.php
> +Route::get('/submit-contact-form/create', function () {
Для проверки POST запроса

2024-02-19 06:30 UTC, FilipovskyAlex approved these changes

2024-02-19 06:30 UTC, merged